### ISSUE TITLE
Standalone application

### ISSUE THREAD

**Issue by edfloreshz** [bq-wrongway/cosmic-noise#1]
Have you considered making a version of this that's a standalone COSMIC application?

**Comment by bq-wrongway** [comment]
> Have you considered making a version of this that's a standalone COSMIC application? 

Yes, i did something like that in pure iced, but for cosmic i changed my mind and i find applet more useful, since you want to start music, interacting with ui is minimal.
Is there any reason you think application would be more useful than applet?

**Comment by edfloreshz** [comment]
I just think that providing users with both options might be nice, but it's totally up to you!

If you want to make an applet instead, please consider implementing `Applet` instead of `Application`

**Comment by bq-wrongway** [comment]
> I just think that providing users with both options might be nice, but it's totally up to you!
> 
> If you want to make an applet instead, please consider implementing `Applet` instead of `Application`

Thanks for the tip about Applet instead of Application.
Regarding other thing il think about it, and see what makes the most sense.

**Comment by edfloreshz** [comment]
Sure thing! I shared your project in [Mattermost](https://chat.pop-os.org), in case you want to join the conversation :)

**Comment by bq-wrongway** [comment]
Hey, not sure how to find what you shared there, its first time im using mattermost il try to check it out.

So i was thinking about making this as full fledged app, in this case i would still like to have "system-tray", so when the app is being pushed to background, or "closed" that it minimizes to system tray. I need to see if this is feasable with cosmic at the moment, since i know that with iced its not possible unless i use some sys-tray from tauri, but then ti still does not feel smooth.

**Comment by edfloreshz** [comment]
It's in the COSMIC Epoch channel.

I'm not sure how to accomplish that, but you could ask in Mattermost, I'm sure someone know how.

**Comment by bq-wrongway** [comment]
@edfloreshz  Hey, sorry to ping you like this, i changed my mine a bit on this, now i have master branch where i plan to have applet, and standalone branch where i have app.
I will finish first error handling for applet (which will also help with application), and then i will need to rework application UI.
if you are curious you can try and check it out as standalone app

**Comment by edfloreshz** [comment]
Will do!
